const { Router } = require('express')
const authRoutes = require('./auth.routes')
const dashboardRoutes = require('./dashboard.routes')
const accountsRoutes = require('./accounts.routes')
const floorsRoutes = require('./floors.routes')
const roomsRoutes = require('./rooms.routes')
const bedsRoutes = require('./beds.routes')
const customersRoutes = require('./customers.routes')
const bookingsRoutes = require('./bookings.routes')
const monthlyPaymentsRoutes = require('./monthlyPayments.routes')
const expensesRoutes = require('./expenses.routes')
const settingsRoutes = require('./settings.routes')
const uploadsRoutes = require('./uploads.routes')
const router = Router()

router.get('/health', (_req, res) => {
  res.json({ success: true, message: 'Roys Hotel API is running', timestamp: new Date().toISOString() })
})

router.use('/auth', authRoutes)
router.use('/dashboard', dashboardRoutes)
router.use('/accounts', accountsRoutes)
router.use('/floors', floorsRoutes)
router.use('/rooms', roomsRoutes)
router.use('/beds', bedsRoutes)
router.use('/customers', customersRoutes)
router.use('/bookings', bookingsRoutes)
router.use('/monthly-payments', monthlyPaymentsRoutes)
router.use('/expenses', expensesRoutes)
router.use('/settings', settingsRoutes)
router.use('/uploads', uploadsRoutes)

module.exports = router