const { Router } = require('express')
const { authenticate } = require('../middleware/auth')
const { anyAdmin } = require('../middleware/role')
const monthlyController = require('../controllers/monthlyController')
const router = Router()

router.use(authenticate, anyAdmin)
router.get('/collection-summary', monthlyController.collectionSummary)
router.get('/export', monthlyController.exportCsv)
router.get('/pending', monthlyController.listPending)
router.get('/paid', monthlyController.listPaid)
router.get('/dues', monthlyController.listDues)
router.get('/:id', monthlyController.getById)
router.get('/', monthlyController.list)
router.post('/', monthlyController.create)
router.put('/:id', monthlyController.update)
router.put('/:id/add-payment', monthlyController.addPayment)
router.post('/:id/mark-paid', monthlyController.markPaid)
router.delete('/:id', monthlyController.remove)

module.exports = router